var x = 110;
var y = 220;
var z = 330;
console.log("Initial values:");
console.log("x:", x);
console.log("y:", y);
console.log("z:", z);
x = 50;
z = 70;
console.log("Modified values:");
console.log("x:", x);
console.log("y:", y);
console.log("z:", z);
